# This is a Docker Compose configuration for local use.

# Run all services:
# docker compose up --build --wait

services:
  api:
    build: .
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8015:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
