$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
      api_jwt_token:
        description: JWT token for accessing the Accounts API as a service
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
  OmnideskSettings:
    additionalProperties: false
    properties:
      base_url:
        description: 'URL in format: https://mydomain.omnidesk.ru'
        title: Base Url
        type: string
      jwt_marker:
        description: 'JWT secret marker for user auth in Omnidesk. See instructions:
          https://support.omnidesk.ru/knowledge_base/item/54180'
        format: password
        title: Jwt Marker
        type: string
        writeOnly: true
    required:
    - base_url
    - jwt_marker
    title: OmnideskSettings
    type: object
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: $Schema
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  accounts:
    $ref: '#/$defs/Accounts'
  omnidesk:
    $ref: '#/$defs/OmnideskSettings'
    description: Omnidesk integration settings
required:
- accounts
- omnidesk
title: Settings
type: object
